### ISSUE TITLE
能安装成功但是配置完成后上传就报错，不启用都能正常使用关闭时间戳也报错

### ISSUE THREAD

**Issue by punkdh** [Dec-F/picgo-plugin-watermark#27]
------Error Stack Begin------
TypeError: Cannot destructure property 'position' of 'config' as it is undefined.
    at Object.exports.parseAndValidate (/Users/denghao/Library/Application Support/picgo/node_modules/picgo-plugin-watermark/lib/util.js:50:13)
    at Object.handle (/Users/denghao/Library/Application Support/picgo/node_modules/picgo-plugin-watermark/lib/index.js:9:124)
    at /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:113:30
    at Array.map (<anonymous>)
    at Lifecycle.handlePlugins (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:110:35)
    at Lifecycle.beforeTransform (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:45:20)
    at Lifecycle.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:23:24)
    at PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:205:53)
    at Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:530756)
    at _e (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:533235)

**Comment by NasTree** [comment]
我也遇到了同样的情况，解决了吗？

**Comment by maxing11** [comment]
解决了吗兄弟

**Comment by PIGGYlit** [comment]
我也是

**Comment by NasTree** [comment]
解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fhyoga/picgo-plugin-watermark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月10日(星期二) 下午3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fhyoga/picgo-plugin-watermark] 能安装成功但是配置完成后上传就报错，不启用都能正常使用关闭时间戳也报错 (Issue #27)





 
我也是
