### ISSUE TITLE
正常安装好无法使用，应该是报字体的错，如图

### ISSUE THREAD

**Issue by RenMu-V** [Dec-F/picgo-plugin-watermark#35]
环境说明：picgo-2.3.1-beta.8，node.js-17.7.0，字体：AozoraMinchoHeavy-2
报错日志：
Error
    at Object.handle (C:\Users\15104\AppData\Roaming\picgo\node_modules\picgo-plugin-watermark\lib\index.js:17:15)
    at C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17789
    at Array.map (<anonymous>)
    at $e.handlePlugins (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17723)
    at $e.beforeTransform (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:16263)
    at $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15869)
    at Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70758)
    at Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653609)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656249)
-------Error Stack End------- 
2022-11-10 08:03:02 [PicGo INFO] Before transform 
2022-11-10 08:03:02 [PicGo INFO] beforeTransformPlugins: watermark running 
2022-11-10 08:03:02 [PicGo ERROR] beforeTransformPlugins: watermark error 
2022-11-10 08:03:02 [PicGo WARN] failed 
2022-11-10 08:03:02 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.handle (C:\Users\15104\AppData\Roaming\picgo\node_modules\picgo-plugin-watermark\lib\index.js:17:15)
    at C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17789
    at Array.map (<anonymous>)
    at $e.handlePlugins (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17723)
    at $e.beforeTransform (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:16263)
    at $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15869)
    at Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70758)
    at Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653609)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656249)
-------Error Stack End------- 
2022-11-10 08:03:02 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.handle (C:\Users\15104\AppData\Roaming\picgo\node_modules\picgo-plugin-watermark\lib\index.js:17:15)
    at C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17789
    at Array.map (<anonymous>)
    at $e.handlePlugins (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17723)
    at $e.beforeTransform (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:16263)
    at $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15869)
    at Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70758)
    at Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653609)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656249)
-------Error Stack End------- 
截图说明：
![2830ed4643adff3dda58cad04300ea81.png](https://img.gejiba.com/images/2830ed4643adff3dda58cad04300ea81.png)
![ccb666fc4649767f745e28d2ebfa23b9.png](https://img.gejiba.com/images/ccb666fc4649767f745e28d2ebfa23b9.png)
![2026d6fdf2f0c6da1e94822a78505849.png](https://img.gejiba.com/images/2026d6fdf2f0c6da1e94822a78505849.png)

**Comment by Kuingsmile** [comment]
[https://github.com/Kuingsmile/PicList](https://github.com/Kuingsmile/PicList)
可以试试我这个，内置水印添加，图片压缩/缩放/旋转和格式转换功能，通过内置sharp实现，无需额外安装
