### ISSUE TITLE
一装这个插件，picgo本体软件就无法启动了

### ISSUE THREAD

**Issue by liub1934** [Dec-F/picgo-plugin-watermark#7]
不管是通过npm安装还是插件管理里面安装都是这样，看了下picgo.log，里面有报错信息
```
2020-01-17 15:52:38 [PicGo ERROR] TypeError: Cannot read property 'format' of undefined
------Error Stack Begin------
TypeError: Cannot read property 'format' of undefined
    at Object.<anonymous> (C:\Users\XXX\AppData\Roaming\picgo\node_modules\sharp\lib\constructor.js:250:22)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\XXX\AppData\Roaming\picgo\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
-------Error Stack End-------
```

**Comment by liub1934** [comment]
picgo版本：2.2.1
NPM版本：6.4.1
node版本：10.15.1
系统：win10

**Comment by liub1934** [comment]
这软件好坑，建议大家在插件插件设置里面进行安装一次，安装完成后picgo软件就打不开了，然后在插件目录运行一次`npm install picgo-plugin-watermark`，就能正常打开软件了并配置插件了。

**Comment by Dec-F** [comment]
@liub1934 使用前请先看readme
![image](https://user-images.githubusercontent.com/20250430/72603493-13c5fd00-3954-11ea-8955-4f520d37378f.png)
